#!/bin/sh
#
# Description:
#    execute commands recursively in all git repository folders
#
git_recursive() {	
  local dir run

  [[ "$1" = "-n" || "$1" = "--dryrun" ]] && shift && run=echo
	
  for f in */.git/; do
    if [[ -d "$f" && ! -L "$f" ]]; then
      dir=$(dirname $f)
      echo ">>> Executing Repository folder './$dir'"
      (pushd $dir 1>/dev/null && $run "$@")
      res=$?
      if [ "$res" -gt 0 ] ; then
        exit $res; 
      fi
    fi
  done
}

git_recursive "$@"