#!/bin/bash
# Update all local branches, checking out each branch in succession.
# Eventually returns to the original branch. Use "-n" for dry-run.

# from http://stackoverflow.com/a/17180894/51264

# Install:
# install as file 'git-update-all' into ~/bin/git/ and add ~/bin/git/ to your PATH or simply execute the command below:
# mkdir -p ~/bin/git >/dev/null && curl -o ~/bin/git/git-update-all -fsSL https://gist.githubusercontent.com/eeichinger/1044107a1126901249b1164dac2fce15/raw/git-update-all && echo '\nNow ensure ~/bin/git is added to your path!'

# Usage:
# git update-all

git_update_all() {
  local run currentBranch
  currentBranch=$(git name-rev --name-only HEAD 2>/dev/null)
  [ "$1" = "-n" ] && shift && run=echo

  for x in $( git branch | cut -c3- ) ; do
     echo ">>> Updating `pwd` git:($x)"
     ($run git checkout $x && $run git pull --ff-only || return 2)
  done

  [ ${#currentBranch} -gt 0 ] && $run git checkout "$currentBranch" >/dev/null
}

git_update_all "$@"