#!/bin/sh
#
# Description:
#    execute git commands recursively in all repository folders
#
# Usage:
#    git recursive [-n|--dryrun] <git command>
#
# Example
#   git recursive remote -v # prints remote info for each git repo
#
git_recursive() {	
  local dir run

  [[ "$1" = "-n" || "$1" = "--dryrun" ]] && shift && run=echo

  DIRS=$(find . -type d -name '.git')
	
  for f in $DIRS; do
    if [[ -d "$f" && ! -L "$f" ]]; then
      dir=$(dirname $f)
      echo ">>> Executing Repository folder '$dir'"
      (pushd $dir 1>/dev/null; $run git --no-pager "$@" || exit 2)
      res=$?
      if [ "$res" -gt 0 ] ; then
	echo "Error: $res"
        #exit $res; 
      fi
    fi
  done
}

git_recursive "$@"
